name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Java 8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8

      - name: Build with Gradle
        run: ./gradlew build

      - name: Generate Test Report
        id: xunit-viewer
        if: always()
        uses: AutoModality/action-xunit-viewer@v1
        with:
          results: ${{ env.TEST_RESULTS_PATH }}
        env:
          TEST_RESULTS_PATH: telegram/build/reports/tests/test/index.html
      - name: Attach the report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Tests report
          path: ${{ steps.xunit-viewer.outputs.report-dir }}
